Vagrant.configure("2") do |config|
  config.vm.define "nodo1" do |nodo1|
    nodo1.vm.box = "bento/ubuntu-16.04"
    nodo1.vm.network "private_network", ip:"192.168.33.11"
    nodo1.vm.hostname = "loadbalancer"
    nodo1.vm.provider "virtualbox" do |vm|
      vm.name = "loadbalancer"
      vm.memory = "256"
      vm.cpus = "1"
    end
  end
  config.vm.define "nodo2" do |nodo2|
    nodo2.vm.box = "bento/ubuntu-16.04"
    nodo2.vm.network "private_network", ip:"192.168.33.12"
    nodo2.vm.hostname = "webserver1"
    nodo2.vm.provider "virtualbox" do |vm|
      vm.name = "webserver1"
      vm.memory = "256"
      vm.cpus = "1"
    end
  end
  config.vm.define "nodo3" do |nodo3|
    nodo3.vm.box = "bento/ubuntu-16.04"
    nodo3.vm.network "private_network", ip:"192.168.33.13"
    nodo3.vm.hostname = "webserver2"
    nodo3.vm.provider "virtualbox" do |vm|
      vm.name = "webserver2"
      vm.memory = "256"
      vm.cpus = "1"
    end
  end
  config.vm.define "nodo4" do |nodo4|
    nodo4.vm.box = "bento/ubuntu-16.04"
    nodo4.vm.network "private_network", ip:"192.168.33.14"
    nodo4.vm.hostname = "dbserver"
    nodo4.vm.provider "virtualbox" do |vm|
      vm.name = "dbserver"
      vm.memory = "256"
      vm.cpus = "1"
    end
  end
end
